### ISSUE TITLE
WARNING:root:No matching PUT was found in the option chain for the strangle.

### ISSUE THREAD

**Issue by Friedrichz** [sirnfs/OptionSuite#3] opened 2019-02-06 03:28 UTC
Hey guys, 
Terrific package, thank you for open-sourcing!
I have been trying to make a test run with the AAPL dataset you kindly provided & the preset strangle strategy... When running it logs the following: 

> WARNING:root:No matching PUT was found in the option chain for the strangle.
>WARNING:root:No matching CALL was found in the option chain for the strangle.
>INFO:root:Net liq: 1000000.000000.
>INFO:root:The AAPL position was closed.

went through the individual modules, but could not discern the problem / haven´t made any changes to the code so far.
He seems to be doing only two iterations in total when handling events
Any idea what might be the issue?

Thank you!

**Comment by sirnfs** [comment] 2019-02-06 05:14
Hi,

The issue is that the sample data provided doesn't the right options chain to run the strangle strategy.  You would normally need to buy the data from iVolatility to get the full dataset, but  I am attaching a five day sample that you can use to get started. 

[RawIV_5day_sample.zip](https://github.com/sirnfs/OptionSuite/files/2834940/RawIV_5day_sample.zip)

Hope this helps you get going.  Let me know if this resolves the issue.

Cheers,

Mike

**Comment by Friedrichz** [comment] 2019-02-06 11:27
Hi Mike, 

Thanks, this one runs through..but it´s the same format right? 
So shouldn´t it be enough to simply change the paths in backTester.py & combineCSV.py as well as the parameters in 'underlying' & 'startTime' ? 

Still getting acquainted with the package so apologize for the noob Qs.
I appreciate it!

**Comment by sirnfs** [comment] 2019-02-06 15:10
Hi,

So the script is looking for ~16 delta puts and calls if you haven't changed the default options.  I don't believe the sample data I provided originally satisfies these requirements.

Thanks,

Mike

**Comment by sirnfs** [comment] 2019-02-11 01:53
Going to go ahead and close this issue, but feel free to create another if there is still an issue.  Thanks!

**Closed by sirnfs** 2019-02-11 01:53 UTC
